package com.ityulkanov;

public class Constants {
    public static final String SAMPLE_STRING = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ut ligula ut orci tincidunt ultricies in vitae libero. Maecenas venenatis lectus ac lectus congue dictum. Aliquam velit diam, viverra nec fermentum sit amet, luctus sed augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis finibus mauris nibh, vitae mattis dolor vulputate nec. Suspendisse orci nulla, rutrum ac rhoncus quis, imperdiet at ligula. Integer et est arcu. Sed eget cursus tortor. In elementum lectus vel molestie fringilla. Mauris vitae hendrerit ex, non porttitor mauris. Proin dapibus ultricies rutrum. Mauris non ante sed tortor ultrices rutrum in quis libero. Sed id neque sed nulla cursus bibendum. Pellentesque rutrum, purus nec aliquet egestas, sapien arcu vulputate metus, non bibendum justo massa eu nisi.\n" +
            "\n" +
            "Sed imperdiet pulvinar dui at porta. Duis non eros id quam tristique accumsan in commodo mi. Nulla placerat faucibus turpis, eu varius dolor auctor eget. Sed a hendrerit metus. Donec orci enim, tempus quis eros et, sodales accumsan nulla. Aenean justo dolor, ultricies eu mattis vel, ullamcorper ac nunc. Sed diam mauris, euismod et enim sit amet, euismod dapibus eros. Donec maximus quis enim eu pulvinar.\n" +
            "\n" +
            "Duis tempus libero vel erat porta, rutrum mattis metus tristique. Aliquam in nisl pharetra massa ultricies vestibulum eget quis est. Phasellus lorem enim, ultrices sit amet tincidunt eget, pretium vitae orci. Nunc dictum vestibulum blandit. Nulla id dignissim erat. Quisque lacinia augue tincidunt nunc pellentesque, sit amet varius orci gravida. Ut efficitur convallis massa eu sagittis. Cras posuere diam nisl, at commodo magna fringilla nec. Sed ac augue viverra, tempus felis at, pellentesque urna. Integer suscipit blandit nisi, id ornare justo feugiat vitae. Sed id ligula faucibus, malesuada magna a, ullamcorper augue. Vivamus libero nisl, finibus iaculis est sit amet, iaculis condimentum erat. Duis nibh sapien, pulvinar vel tellus at, consectetur tristique justo. Proin blandit sollicitudin orci, id egestas libero lobortis dapibus. Nulla turpis arcu, volutpat ut est sed, malesuada molestie ex. Maecenas vehicula massa ac tortor ornare bibendum.\n" +
            "\n" +
            "Suspendisse potenti. Sed vel viverra ex. Pellentesque dignissim auctor dignissim. Donec venenatis, urna et dictum eleifend, metus magna euismod tortor, in eleifend dui magna nec sapien. Morbi eget felis vitae tortor sollicitudin accumsan non eget dolor. Quisque molestie, justo at tristique lobortis, magna metus posuere enim, tincidunt faucibus risus odio nec mi. Nullam odio felis, semper quis sodales eu, rhoncus non quam.\n" +
            "\n" +
            "Nullam consequat odio eget sapien lobortis pellentesque. Nunc id ex dui. Integer rutrum ullamcorper rhoncus. Integer et volutpat lorem. Ut in justo id erat mattis maximus eu sit amet risus. Duis id ex eu velit volutpat finibus ac eget est. Phasellus ut euismod mi. Praesent commodo accumsan augue vitae consectetur. Quisque et magna consequat, fermentum quam vulputate, dictum ex. Aliquam erat volutpat. Morbi eu condimentum erat. Quisque ipsum urna, dictum nec consectetur vel, pretium id sapien. Praesent felis neque, interdum ut pulvinar sit amet, sodales in quam. Mauris quis congue nisl, ultrices vestibulum quam. Duis ornare convallis orci. Suspendisse volutpat ante sit amet ultrices gravida.";
    public static final String SAMPLE_SECOND_STRING = "Aenean laoreet malesuada tellus, quis imperdiet lacus pretium euismod. Integer eu lacus nibh. Nulla accumsan interdum sem, at malesuada neque rutrum vel. Donec nec lacus nec neque scelerisque mattis non nec mauris. Quisque dolor leo, suscipit et libero vel, lobortis fermentum neque. Vestibulum quis bibendum elit, facilisis elementum nulla. Nam pulvinar eros ut gravida dapibus.\n" +
            "\n" +
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer auctor odio at semper euismod. In nunc nisi, posuere nec mattis non, lobortis non nisi. Aenean aliquet eu eros vel gravida. Sed a arcu sem. Donec est sem, eleifend eu velit eu, pretium eleifend elit. Suspendisse et consectetur diam, quis consectetur odio.\n" +
            "\n" +
            "Donec porta felis nulla. Donec mattis turpis in varius pretium. Nulla facilisi. Phasellus venenatis placerat vulputate. Nunc sollicitudin quis metus eget gravida. Nam et arcu maximus, dignissim massa a, fringilla augue. In hac habitasse platea dictumst. Duis egestas lacus vel lectus hendrerit bibendum. Vivamus et tristique turpis. Aenean sed est non ex porttitor pellentesque. Duis tempus vestibulum urna, eu semper purus.\n" +
            "\n" +
            "Proin non auctor quam, at volutpat elit. Pellentesque sollicitudin, orci id maximus pellentesque, diam elit tristique urna, blandit rutrum nulla sem nec diam. Curabitur gravida finibus ligula, eu convallis ligula euismod nec. Sed in lacus mollis, convallis est sed, elementum leo. Etiam ac diam egestas, semper lectus cursus, interdum dui. Etiam sed mi lorem. Duis viverra mauris turpis. Ut dui tellus, pulvinar congue elementum vitae, mollis vitae nibh. Suspendisse id augue ornare, bibendum odio ut, elementum turpis. Integer nibh turpis, ultricies at dapibus vitae, egestas eu nisi. Morbi ut vestibulum nibh, non condimentum purus. Vestibulum aliquam nibh sed sem mollis tincidunt. Pellentesque sollicitudin ultrices orci, a tempus mauris pretium vel. Vivamus porttitor tellus sed nisi ullamcorper hendrerit. Aliquam pharetra porta nulla id laoreet.\n" +
            "\n" +
            "Cras est lacus, auctor vitae pulvinar a, placerat ut augue. Donec aliquet eu urna nec ornare. Nullam luctus ante ac erat rutrum, a rhoncus sapien tempus. Nam ipsum tortor, laoreet quis tempor ut, interdum vel lacus. Pellentesque rutrum arcu sem, a gravida ligula sollicitudin ac. Nam quis aliquam turpis, egestas iaculis odio. Maecenas vehicula diam justo, et finibus nisl gravida eget.Aenean laoreet malesuada tellus, quis imperdiet lacus pretium euismod. Integer eu lacus nibh. Nulla accumsan interdum sem, at malesuada neque rutrum vel. Donec nec lacus nec neque scelerisque mattis non nec mauris. Quisque dolor leo, suscipit et libero vel, lobortis fermentum neque. Vestibulum quis bibendum elit, facilisis elementum nulla. Nam pulvinar eros ut gravida dapibus.\n" +
            "\n" +
            "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer auctor odio at semper euismod. In nunc nisi, posuere nec mattis non, lobortis non nisi. Aenean aliquet eu eros vel gravida. Sed a arcu sem. Donec est sem, eleifend eu velit eu, pretium eleifend elit. Suspendisse et consectetur diam, quis consectetur odio.\n" +
            "\n" +
            "Donec porta felis nulla. Donec mattis turpis in varius pretium. Nulla facilisi. Phasellus venenatis placerat vulputate. Nunc sollicitudin quis metus eget gravida. Nam et arcu maximus, dignissim massa a, fringilla augue. In hac habitasse platea dictumst. Duis egestas lacus vel lectus hendrerit bibendum. Vivamus et tristique turpis. Aenean sed est non ex porttitor pellentesque. Duis tempus vestibulum urna, eu semper purus.\n" +
            "\n" +
            "Proin non auctor quam, at volutpat elit. Pellentesque sollicitudin, orci id maximus pellentesque, diam elit tristique urna, blandit rutrum nulla sem nec diam. Curabitur gravida finibus ligula, eu convallis ligula euismod nec. Sed in lacus mollis, convallis est sed, elementum leo. Etiam ac diam egestas, semper lectus cursus, interdum dui. Etiam sed mi lorem. Duis viverra mauris turpis. Ut dui tellus, pulvinar congue elementum vitae, mollis vitae nibh. Suspendisse id augue ornare, bibendum odio ut, elementum turpis. Integer nibh turpis, ultricies at dapibus vitae, egestas eu nisi. Morbi ut vestibulum nibh, non condimentum purus. Vestibulum aliquam nibh sed sem mollis tincidunt. Pellentesque sollicitudin ultrices orci, a tempus mauris pretium vel. Vivamus porttitor tellus sed nisi ullamcorper hendrerit. Aliquam pharetra porta nulla id laoreet.\n" +
            "\n" +
            "Cras est lacus, auctor vitae pulvinar a, placerat ut augue. Donec aliquet eu urna nec ornare. Nullam luctus ante ac erat rutrum, a rhoncus sapien tempus. Nam ipsum tortor, laoreet quis tempor ut, interdum vel lacus. Pellentesque rutrum arcu sem, a gravida ligula sollicitudin ac. Nam quis aliquam turpis, egestas iaculis odio. Maecenas vehicula diam justo, et finibus nisl gravida eget.";
}
